name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    env:
      CHEZ_SCHEME_VERSION: '9.6.4'
    strategy:
      matrix:
        os: [macos, ubuntu, windows]

    steps:
      - uses: actions/checkout@v2
      - name: Chez cache
        id: shen-scheme-chez-cache
        uses: actions/cache@v2
        with:
          path: _build/chez
          key: ${{ matrix.os }}-chez-${{ env.CHEZ_SCHEME_VERSION }}
      - name: Install deps (Ubuntu)
        run: sudo apt-get install -y uuid-dev
        if: runner.os == 'linux'
      - name: Build and test
        run: |
          echo "Using Chez Scheme version $CHEZ_SCHEME_VERSION"
          make fetch-kernel
          make fetch-prebuilt
          make precompile-with-prebuilt
          make csversion=$CHEZ_SCHEME_VERSION
          make test
