name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [macos, ubuntu, windows]

    steps:
      - uses: actions/checkout@v2
      - name: Chez cache
        id: shen-scheme-chez-cache
        uses: actions/cache@v2
        with:
          path: _build/chez
          key: ${{ matrix.os }}
      - name: Install deps (Ubuntu)
        run: sudo apt-get install -y uuid-dev
        if: runner.os == 'linux'
      - name: Build and test
        run: |
          make fetch-kernel
          make fetch-prebuilt
          make precompile
          make
          make test
