on:
  push:
    tags:
    - 'v*.*.*'
    - 'v*.*'

name: Make release

jobs:
  build:
    name: Upload Release Asset (${{ matrix.OSNAME }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: macos
            BUNDLE_EXT: tar.gz
            ASSET_CONTENT_TYPE: application/gzip
            OSNAME: macOS
          - os: ubuntu
            BUNDLE_EXT: tar.gz
            ASSET_CONTENT_TYPE: application/gzip
            OSNAME: linux
          - os: windows
            BUNDLE_EXT: zip
            ASSET_CONTENT_TYPE: application/zip
            OSNAME: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set release version in env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Chez cache
        id: shen-scheme-chez-cache
        uses: actions/cache@v2
        with:
          path: _build/chez
          key: shen-scheme-chez-cache-${{ matrix.os }}
      - name: Install deps (Ubuntu)
        run: sudo apt-get install -y uuid-dev
        if: runner.os == 'linux'
      - name: Build and test
        run: |
          make fetch-kernel
          make fetch-prebuilt
          make precompile
          make
          make test
      - name: Create binary release for ${{ matrix.os }}
        run: make binary-release
      - name: Create source release
        if: runner.os == 'linux'
        run: make source-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ RELEASE_VERSION }}
          draft: true
          prerelease: false
      - name: Upload Release Asset (binary for ${{ matrix.OSNAME }})
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/shen-scheme-${{ RELEASE_VERSION }}-${{ matrix.OSNAME }}-bin.${{ matrix.BUNDLE_EXT }}
          asset_name: shen-scheme-${{ RELEASE_VERSION }}-${{ matrix.OSNAME }}-bin.${{ matrix.BUNDLE_EXT }}
          asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}
      - name: Upload Release Asset (sources)
        if: runner.os == 'linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_dist/shen-scheme-${{ RELEASE_VERSION }}-src.${{ matrix.BUNDLE_EXT }}
          asset_name: shen-scheme-${{ RELEASE_VERSION }}-src.${{ matrix.BUNDLE_EXT }}
          asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}